// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQNm9HOup_VoiYc-MVHxE0NxiPPasWD3g',
    appId: '1:844741810062:web:0ec565f0d735b27bfe76df',
    messagingSenderId: '844741810062',
    projectId: 'lapetaje-chat-app',
    authDomain: 'lapetaje-chat-app.firebaseapp.com',
    storageBucket: 'lapetaje-chat-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9B0zsQ3dGEpOOJMIZlo8iolVzchu2onw',
    appId: '1:844741810062:android:6c6f8f696546187ffe76df',
    messagingSenderId: '844741810062',
    projectId: 'lapetaje-chat-app',
    storageBucket: 'lapetaje-chat-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA1fAwZFGHGll2J03M03eA8NMspC-bs10',
    appId: '1:844741810062:ios:9731809eaa5ce2f3fe76df',
    messagingSenderId: '844741810062',
    projectId: 'lapetaje-chat-app',
    storageBucket: 'lapetaje-chat-app.appspot.com',
    iosClientId:
        '844741810062-o33eescoe1hf0mtdgn2ag8brnavlod6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
